### ISSUE TITLE
Create Authentication layer

### ISSUE THREAD

**Issue by psagan** [psagan/coffeeword#6]

**Comment by jb3** [comment]
Hey there @psagan, where should the Authorization layer be added?

**Comment by psagan** [comment]
Hi, the project is in early stage, so at the beginning thank you for interest 😃 
I will provide more description in readme soon. 

So, brief explanation: 
The concept is to create simple, publishing platform to give authors possibility to create articles. 
I think at the beginning that classical html reloads will be ok. 

Idea of this task is to add possibility to log in and log out users via Login form and logout button (via classical cookie and session) + add possibility (via Plug) to protect actions in controllers.

In the further evaluation there will be need to create something like invitation system (?), that admin can invite other authors ( this is an idea, open for discussion). As this is publication platform - I think there won't be open registration for everyone, so invitations can work in this case.

I've already created users CRUD structure: https://github.com/psagan/coffeeword/pull/7/files and implemented  password hashing: https://github.com/psagan/coffeeword/pull/9/files (I will create tests for that in next commits). But this is the beginning to start.
